notifications:
  email: false

sudo: required

services:
  - docker

language: python

before_install:
 - docker build -t iosonofabio/singlecell-container .
 - docker cp tests iosonofabio/singlecell-container:/
 - docker cp example_data iosonofabio/singlecell-container:/

script:
 - docker run iosonofabio/singlecell-container /bin/sh -c /tests/test_STAR_htseq-count_yeast.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push iosonofabio/singlecell-container;
    fi
