notifications:
  email: false

sudo: required

services:
  - docker

language: python

before_install:
 - docker build -t iosonofabio/singlecell .

script:
 - echo "Got here!"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push iosonofabio/singlecell-container;
    fi
